---

- hosts: all
  become: true
  tasks:

    # if a linux distro is not Ubuntu or Debian based
    # meaning apt does not exist it will be skipped
    # when: ansible_distribution == "Ubuntu"
    # when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: install apache and php
    package:
      name: 
        # - apache2
        # - libapache2-mod-php
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
    # when: ansible_distribution == "Ubuntu"